version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.16

executors:
  default:
    docker:
      - image: cimg/go:1.18.1-node

aliases:
  - &restore_go_cache
    restore_cache:
      key: go-mod-v2-{{ checksum "go.sum" }}
  - &save_go_cache
    save_cache:
      key: go-mod-v2-{{ checksum "go.sum" }}
      paths:
        - /go/pkg/mod

commands:
  npm-dependencies:
    description: "Get JavaScript dependencies"
    steps:
      - restore_cache:
          name: Restore npm cache
          key: v3-npm-{{ checksum "./webapp/package-lock.json" }}-{{ arch }}
      - run:
          name: Getting JavaScript dependencies
          command: |
            cd webapp
            NODE_ENV=development npm install --ignore-scripts --no-save
      - save_cache:
          name: Save npm cache
          key: v3-npm-{{ checksum "./webapp/package-lock.json" }}-{{ arch }}
          paths:
            - ./webapp/node_modules

  save:
    description: "Save binaries artifacts"
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Copying artifacts
          command: |
            mkdir -p /tmp/artifacts
            cp dist/<<parameters.filename>> /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

jobs:
  lint:
    executor:
      name: default
    resource_class: large
    steps:
      - checkout
      - *restore_go_cache
      - npm-dependencies
      - run:
          name: Checking code style
          command: |
            make check-style
      - run: go mod tidy -v
      - run:
          name: Checking diff of go mod files
          command: |
            git --no-pager diff --exit-code go.mod go.sum || (echo "Please run \"go mod tidy\" and commit the changes in go.mod and go.sum." && exit 1)
      - run: make apply
      - run:
          name: Checking diff of generated manifest files
          command: |
            git --no-pager diff --exit-code *manifest.* || (echo "Please run \"make apply\" and commit the changes in the generated manifests." && exit 1)
      - run: make i18n-extract-webapp
      - run:
          name: Checking diff of webapp i18n files
          command: |
            git --no-pager diff --exit-code webapp/i18n/en.json || (echo "Please run \"make i18n-extract\" and commit the changes in webapp/i18n/en.json." && exit 1)

      - *save_go_cache

  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Getting JavaScript dependencies
          command: |
            cd webapp
            NODE_ENV=development npm install --ignore-scripts --no-save
      - run:
          name: Building Plugin Bundle
          command: |
            make dist
      - save:
          filename: "*.tar.gz"
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
             - .

  release-github:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on Github"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} /tmp/artifacts/

workflows:
  version: 2
  ci:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - lint
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - release-github:
          context: wellsite-server-rebranding-automation
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - lint
            - build
